# Generated by Django 6.0.6 on 2026-06-18 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_polls', to='chaos.track'),
        ),
        migrations.AlterField(
            model_name='track',
            name='youtube_video_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
