# Generated by Django 6.0.6 on 2026-06-18 15:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaos', '0002_poll_ends_at_poll_winner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='ends_at',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='winner',
        ),
        migrations.AddField(
            model_name='poll',
            name='channel_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='chaos.poll'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='chaos.track'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['poll'], name='chaos_vote_poll_id_fde69a_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['track'], name='chaos_vote_track_i_085e0b_idx'),
        ),
    ]
