# Generated by Django 6.0.6 on 2026-06-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaos', '0003_remove_poll_ends_at_remove_poll_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['slack_user_id'], name='chaos_vote_slack_u_a78c0a_idx'),
        ),
    ]
