# Generated by Django 6.0.6 on 2026-06-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaos', '0004_poll_ended_at_vote_chaos_vote_slack_u_a78c0a_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='leaderboard_ts',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
