# Generated by Django 6.0.6 on 2026-06-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaos', '0005_poll_leaderboard_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='message_ts',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
