# Generated by Django 6.0.6 on 2026-06-19 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaos', '0006_poll_message_ts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='leaderboard_ts',
        ),
    ]
