# Generated by Django 6.0.6 on 2026-06-19 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chaos', '0007_remove_poll_leaderboard_ts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='message_ts',
            new_name='leaderboard_ts',
        ),
    ]
