# Generated by ChatGPT
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('chaos', '0009_add_kiosk_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='recapped',
            field=models.BooleanField(default=False),
        ),
    ]
